---
    - name: update sysctl param
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
        ignoreerrors: yes
      with_items:
        - { name: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
        - { name: 'net.ipv6.conf.default.disable_ipv6',value: '1' }
        - { name: 'fs.file-max',value: '2097152' }
        - { name: 'fs.suid_dumpable',value: '0' }
        - { name: 'kernel.msgmnb',value: '65536' }
        - { name: 'kernel.msgmax',value: '65536' }
        - { name: 'kernel.shmmax',value: '68719476736' }
        - { name: 'kernel.shmall',value: '4294967296' }
        - { name: 'kernel.sysrq',value: '0' }
        - { name: 'kernel.core_uses_pid',value: '1' }
        - { name: 'net.core.somaxconn',value: '65535' }
        - { name: 'net.core.netdev_max_backlog',value: '262144' }
        - { name: 'net.core.optmem_max',value: '25165824' }
        - { name: 'net.core.rmem_default',value: '31457280' }
        - { name: 'net.core.rmem_max',value: '67108864' }
        - { name: 'net.core.wmem_default',value: '31457280' }
        - { name: 'net.core.wmem_max',value: '67108864' }
        - { name: 'net.ipv4.tcp_max_tw_buckets',value: '6000' }
        - { name: 'net.ipv4.tcp_sack',value: '1' }
        - { name: 'net.ipv4.tcp_window_scaling',value: '1' }
        - { name: 'net.ipv4.tcp_rme',value: '10240 87380 12582912' }
        - { name: 'net.ipv4.tcp_wme',value: '10240 87380 12582912' }
        - { name: 'net.ipv4.ip_local_port_range',value: '1024 65535' }
        - { name: 'net.ipv4.tcp_keepalive_time',value: '30' }
        - { name: 'net.ipv4.tcp_max_syn_backlog',value: '262144' }
        - { name: 'net.ipv4.tcp_timestamps',value: '0' }
        - { name: 'net.ipv4.tcp_synack_retries',value: '1' }
        - { name: 'net.ipv4.tcp_syn_retries',value: '1' }
        - { name: 'net.ipv4.tcp_tw_recycle',value: '1' }
        - { name: 'net.ipv4.tcp_tw_reuse',value: '1' }
        - { name: 'net.ipv4.tcp_mem',value: '94500000 915000000 927000000' }
        - { name: 'net.ipv4.tcp_fin_timeout',value: '1' }
        - { name: 'net.ipv4.tcp_max_orphans',value: '3276800' }
        - { name: 'net.ipv4.tcp_syncookies',value: '1' }
        - { name: 'vm.dirty_background_ratio',value: '5' }
        - { name: 'vm.dirty_ratio',value: '10' }
        - { name: 'vm.swappines',value: '2' }
        - { name: 'net.ipv4.ip_forward',value: '1' }
