---
- hosts:
   - name: install Docker
     yum:
       name: docker
       state: present
       update_cache: true

   - name: start Docker
     systemd:
       name: docker
       enabled: yes
       state: started

   - name: configure docker proxy
     blockinfile:
       path: /etc/sysconfig/docker
       block: |
         http_proxy="http://172.16.8.1:3128"
         https_proxy="http://172.16.8.1:3128"
         no_proxy="localhost,127.0.0.0/8,172.16.0.0/16,172.18.0.0/16,172.18.31.28"
         #ADD_REGISTRY='--add-registry daocloud.io'
         INSECURE_REGISTRY='--insecure-registry 172.18.31.28'

   - name: Allow access to insecure registry
     lineinfile:
       dest: /etc/sysconfig/docker
       regexp: ^OPTIONS=
       line: OPTIONS='--selinux-enabled --log-driver=journald --signature-verification=false --registry-mirror=https://registry.docker-cn.com --registry-mirror=https://docker.mirrors.ustc.edu.cn'
     notify: restart docker
